// Generated by uniffi-bindgen-react-native
// Modified to support old architecture (RCT_NEW_ARCH_ENABLED=0)
//
// This file is maintained in overrides/ and copied after generation.

#import "MattermostE2ee.h"

#ifndef RCT_NEW_ARCH_ENABLED
// Old architecture needs bridge access
#import <React/RCTBridge+Private.h>
#import <ReactCommon/RCTTurboModule.h>
#import <jsi/jsi.h>

using namespace facebook;
#endif

// Don't compile this code when we build for the old architecture.
#ifdef RCT_NEW_ARCH_ENABLED

namespace uniffi_generated {
    using namespace facebook::react;
    /**
    * ObjC++ class for module 'NativeMattermostE2ee'
    */
    class JSI_EXPORT NativeMattermostE2eeSpecJSI : public ObjCTurboModule {
    public:
        NativeMattermostE2eeSpecJSI(const ObjCTurboModule::InitParams &params);
        std::shared_ptr<CallInvoker> callInvoker;
    };

    static facebook::jsi::Value __hostFunction_MattermostE2ee_installRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        auto& tm = static_cast<NativeMattermostE2eeSpecJSI&>(turboModule);
        auto jsInvoker = tm.callInvoker;
        uint8_t result = mattermoste2ee::installRustCrate(rt, jsInvoker);
        return facebook::jsi::Value(rt, result);
    }
    static facebook::jsi::Value __hostFunction_MattermostE2ee_cleanupRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        uint8_t result = mattermoste2ee::cleanupRustCrate(rt);
        return facebook::jsi::Value(rt, result);
    }

    NativeMattermostE2eeSpecJSI::NativeMattermostE2eeSpecJSI(const ObjCTurboModule::InitParams &params)
        : ObjCTurboModule(params), callInvoker(params.jsInvoker) {
            this->methodMap_["installRustCrate"] = MethodMetadata {1, __hostFunction_MattermostE2ee_installRustCrate};
            this->methodMap_["cleanupRustCrate"] = MethodMetadata {1, __hostFunction_MattermostE2ee_cleanupRustCrate};
    }
} // namespace uniffi_generated

#endif

@implementation MattermostE2ee

@synthesize bridge = _bridge;
@synthesize methodQueue = _methodQueue;

RCT_EXPORT_MODULE()

#ifndef RCT_NEW_ARCH_ENABLED
// Old architecture: Access JSI runtime through the bridge
RCT_EXPORT_SYNCHRONOUS_TYPED_METHOD(NSNumber *, installRustCrate)
{
  RCTCxxBridge *cxxBridge = (RCTCxxBridge *)self.bridge;
  if (!cxxBridge.runtime) {
    return @(NO);
  }

  jsi::Runtime &rt = *(jsi::Runtime *)cxxBridge.runtime;
  auto jsInvoker = cxxBridge.jsCallInvoker;
  uint8_t result = mattermoste2ee::installRustCrate(rt, jsInvoker);
  return @(result);
}

RCT_EXPORT_SYNCHRONOUS_TYPED_METHOD(NSNumber *, cleanupRustCrate)
{
  RCTCxxBridge *cxxBridge = (RCTCxxBridge *)self.bridge;
  if (!cxxBridge.runtime) {
    return @(NO);
  }

  jsi::Runtime &rt = *(jsi::Runtime *)cxxBridge.runtime;
  uint8_t result = mattermoste2ee::cleanupRustCrate(rt);
  return @(result);
}
#else
// New architecture: Use TurboModule

// Automated testing checks mattermoste2ee
// by comparing the whole line here.
/*
- (NSNumber *)multiply:(double)a b:(double)b {
    NSNumber *result = @(mattermoste2ee::multiply(a, b));
}
*/

- (NSNumber *)installRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (NSNumber *)cleanupRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<uniffi_generated::NativeMattermostE2eeSpecJSI>(params);
}
#endif

@end
