// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

export const MIN_CHANNEL_NAME_LENGTH = 1;
export const MAX_CHANNEL_NAME_LENGTH = 64;
export const IGNORE_CHANNEL_MENTIONS_ON = 'on';
export const IGNORE_CHANNEL_MENTIONS_OFF = 'off';
export const IGNORE_CHANNEL_MENTIONS_DEFAULT = 'default';
export const CHANNEL_AUTO_FOLLOW_THREADS_TRUE = 'on';
export const CHANNEL_AUTO_FOLLOW_THREADS_FALSE = 'off';

export default {
    IGNORE_CHANNEL_MENTIONS_ON,
    IGNORE_CHANNEL_MENTIONS_OFF,
    IGNORE_CHANNEL_MENTIONS_DEFAULT,
    MAX_CHANNEL_NAME_LENGTH,
    MIN_CHANNEL_NAME_LENGTH,
    CHANNEL_AUTO_FOLLOW_THREADS_TRUE,
    CHANNEL_AUTO_FOLLOW_THREADS_FALSE,
};
