// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

module.exports = [
    './node_modules/app/actions/navigation/index.js',
    './node_modules/app/constants/deep_linking.js',
    './node_modules/app/constants/device.js',
    './node_modules/app/constants/index.js',
    './node_modules/app/constants/list.js',
    './node_modules/app/constants/navigation.js',
    './node_modules/app/constants/post_textbox.js',
    './node_modules/app/constants/types.js',
    './node_modules/app/constants/view.js',
    './node_modules/app/constants/websocket.ts',
    './node_modules/app/init/analytics.ts',
    './node_modules/app/init/credentials.js',
    './node_modules/app/init/device.ts',
    './node_modules/app/init/emm_provider.js',
    './node_modules/app/init/fetch.js',
    './node_modules/app/init/global_event_handler.js',
    './node_modules/app/init/push_notifications.ts',
    './node_modules/app/mattermost.js',
    './node_modules/app/mattermost_managed/index.js',
    './node_modules/app/mattermost_managed/mattermost-managed.android.js',
    './node_modules/app/screens/index.js',
    './node_modules/app/store/ephemeral_store.js',
    './node_modules/app/store/helpers.ts',
    './node_modules/app/store/index.ts',
    './node_modules/app/store/initial_state.js',
    './node_modules/app/store/middlewares/helpers.js',
    './node_modules/app/store/middlewares/index.ts',
    './node_modules/app/store/middlewares/message_retention.js',
    './node_modules/app/store/middlewares/sentry.js',
    './node_modules/app/store/middlewares/thunk.js',
    './node_modules/app/store/mmkv_adapter.ts',
    './node_modules/app/store/store.ts',
    './node_modules/app/store/utils.js',
    './node_modules/share_extension/android/index.js',
];
