name: prepare-mobile-build
description: Action to prepare environment for mobile build

runs:
  using: composite
  steps:
    # The required ruby version is mentioned in '.ruby-version'
    - uses: ruby/setup-ruby@32110d4e311bd8996b2a82bf2a43b714ccc91777 # v1.221.0

    - name: ci/setup-fastlane-dependencies
      shell: bash
      run: |
        echo "::group::setup-fastlane-dependencies"
        bundle install
        echo "::endgroup::"
      working-directory: ./fastlane

    - name: Cache Ruby gems
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: ci/prepare-node-deps
      uses: ./.github/actions/prepare-node-deps
