source "https://rubygems.org"

gem "fastlane"
gem "nokogiri", '~> 1.18.4'
gem "dotenv"

plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
