source "https://rubygems.org"

gem "fastlane", ">= 2.222.0"
gem "nokogiri"
gem "dotenv"

plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
