source "https://rubygems.org"

gem "fastlane", "2.141.0"
gem "nokogiri"
gem "aws-sdk-s3"

plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
