name: prepare-rust-toolchain
description: Install Rust toolchain and build E2EE module for mobile platforms

inputs:
  platform:
    description: 'Platform to build for: ios or android'
    required: true

runs:
  using: composite
  steps:
    - name: ci/setup-rust-toolchain
      id: rust-toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        targets: ${{ inputs.platform == 'ios' && 'aarch64-apple-ios,aarch64-apple-ios-sim,x86_64-apple-ios' || 'aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android' }}

    - name: ci/cache-rust-artifacts
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          libraries/@mattermost/e2ee/rust/target/
        key: ${{ runner.os }}-cargo-${{ inputs.platform }}-${{ steps.rust-toolchain.outputs.cachekey }}-${{ hashFiles('libraries/@mattermost/e2ee/rust/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ inputs.platform }}-${{ steps.rust-toolchain.outputs.cachekey }}-
          ${{ runner.os }}-cargo-${{ inputs.platform }}-

    - name: ci/install-cargo-ndk
      if: inputs.platform == 'android'
      shell: bash
      run: |
        echo "::group::install-cargo-ndk"
        if ! command -v cargo-ndk &> /dev/null; then
          echo "Installing cargo-ndk..."
          cargo install cargo-ndk
        else
          echo "cargo-ndk already installed"
        fi
        echo "::endgroup::"

    - name: ci/test-rust-unit
      shell: bash
      run: |
        echo "::group::test-rust-unit"
        npm run e2ee:test:rust
        echo "::endgroup::"

    - name: ci/build-e2ee-module
      shell: bash
      run: |
        echo "::group::build-e2ee-module (${{ inputs.platform }})"
        npm run e2ee:build
        echo "::endgroup::"

    - name: ci/verify-e2ee-build
      shell: bash
      run: |
        echo "::group::verify-e2ee-build"
        npm run e2ee:test
        echo "::endgroup::"

    - name: ci/test-e2ee-native
      shell: bash
      run: |
        echo "::group::test-e2ee-native (${{ inputs.platform }})"
        if [[ "${{ inputs.platform }}" == "ios" ]]; then
          npm run e2ee:test:ios
        else
          npm run e2ee:test:android
        fi
        echo "::endgroup::"
