name: prepare-android-build
description: Action to prepare environment for android build

inputs:
  e2ee-enabled:
    description: 'Enable E2EE features'
    required: false
    default: 'false'
  sign:
    description: Flag to enable android package signing
    default: "true"

runs:
  using: composite
  steps:
    - name: ci/prepare-mobile-build
      uses: ./.github/actions/prepare-mobile-build

    - name: ci/apply-16kb-pagesize-patch
      shell: bash
      run: |
        echo "::group::Apply 16KB page size compatibility patch"
        npm run apply-16kb-pagesize-patch
        echo "::endgroup::"

    - name: ci/setup-e2ee
      if: inputs.e2ee-enabled == 'true'
      shell: bash
      run: npm run e2ee:enable -- ci

    - name: ci/clear-android-autolinking-cache
      if: inputs.e2ee-enabled == 'true'
      shell: bash
      run: |
        echo "::group::Clear Android autolinking cache for E2EE"
        rm -rf android/.gradle android/build/generated/autolinking
        echo "::endgroup::"

    - name: ci/setup-java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "17"

    - name: ci/jetify-android-libraries
      shell: bash
      run: |
        echo "::group::jetify-android-libraries"
        ./node_modules/.bin/jetify
        echo "::endgroup::"

    - name: ci/checkout-private-repo
      if: ${{ inputs.sign == 'true' }}
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: mattermost/mattermost-mobile-private
        token: ${{ env.MATTERMOST_BUILD_GH_TOKEN }}
        path: ${{ github.workspace }}/mattermost-mobile-private

    - name: ci/append-keystore-to-android-build-for-signing
      if: ${{ inputs.sign == 'true' }}
      shell: bash
      run: |
        echo "::group::append-keystore-to-android-build-for-signing"
        cp ${{ github.workspace }}/mattermost-mobile-private/android/${STORE_FILE} android/app/${STORE_FILE}
        echo "" | tee -a android/gradle.properties > /dev/null
        echo MATTERMOST_RELEASE_STORE_FILE=${STORE_FILE} | tee -a android/gradle.properties > /dev/null
        echo ${STORE_ALIAS} | tee -a android/gradle.properties > /dev/null
        echo ${STORE_PASSWORD} | tee -a android/gradle.properties > /dev/null
        echo "::endgroup::"
