// Generated by uniffi-bindgen-react-native
#include "mattermost-e2ee.h"
#include "generated/mattermost_e2ee.hpp"

namespace mattermoste2ee {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeMattermostE2ee::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}