# Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
# See LICENSE.txt for license information.

name: Setup E2EE SSH Key
description: Configure SSH key for E2EE submodule repository access

inputs:
  ssh-private-key:
    description: 'SSH private key for E2EE submodule repository access'
    required: true

runs:
  using: composite
  steps:
    - name: Setup SSH key for E2EE submodule
      shell: bash
      run: |
        echo "::group::Setup E2EE SSH key"
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh-private-key }}" > ~/.ssh/e2ee_submodule_ed25519
        chmod 600 ~/.ssh/e2ee_submodule_ed25519

        # Add GitHub to known hosts
        ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null

        echo "✅ SSH key configured for E2EE submodule"
        echo "::endgroup::"
