# Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
# See LICENSE.txt for license information.

name: Setup SSH Key
description: Configure SSH private key for accessing private repositories

inputs:
  ssh-private-key:
    description: 'SSH private key for repository access'
    required: true

runs:
  using: composite
  steps:
    - name: Configure SSH private key
      shell: bash
      run: |
        SSH_KEY_PATH=~/.ssh/id_ed25519
        mkdir -p ~/.ssh
        echo -e '${{ inputs.ssh-private-key }}' > ${SSH_KEY_PATH}
        chmod 0600 ${SSH_KEY_PATH}
        ssh-keygen -y -f ${SSH_KEY_PATH} > ${SSH_KEY_PATH}.pub
        echo "✅ SSH key configured"
