// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import {AppSchema, appSchema} from '@nozbe/watermelondb';

import {
    CategorySchema,
    CategoryChannelSchema,
    ChannelInfoSchema,
    ChannelMembershipSchema,
    ChannelSchema,
    CustomEmojiSchema,
    DraftSchema,
    FileSchema,

    // groups: MM-41882 GroupMembershipSchema,
    // groups: MM-41882 GroupSchema,
    // groups: MM-41882 GroupsChannelSchema,
    // groups: MM-41882 GroupsTeamSchema,
    MyChannelSchema,
    MyChannelSettingsSchema,
    MyTeamSchema,
    PostInThreadSchema,
    PostSchema,
    PostsInChannelSchema,
    PreferenceSchema,
    ReactionSchema,
    RoleSchema,
    SlashCommandSchema,
    SystemSchema,
    TeamChannelHistorySchema,
    TeamMembershipSchema,
    TeamSchema,
    TeamSearchHistorySchema,
    TermsOfServiceSchema,
    UserSchema,
} from './table_schemas';

export const serverSchema: AppSchema = appSchema({
    version: 1,
    tables: [
        CategorySchema,
        CategoryChannelSchema,
        ChannelInfoSchema,
        ChannelMembershipSchema,
        ChannelSchema,
        CustomEmojiSchema,
        DraftSchema,
        FileSchema,

        // groups: MM-41882 GroupMembershipSchema,
        // groups: MM-41882 GroupSchema,
        // groups: MM-41882 GroupsChannelSchema,
        // groups: MM-41882 GroupsTeamSchema,
        MyChannelSchema,
        MyChannelSettingsSchema,
        MyTeamSchema,
        PostInThreadSchema,
        PostSchema,
        PostsInChannelSchema,
        PreferenceSchema,
        ReactionSchema,
        RoleSchema,
        SlashCommandSchema,
        SystemSchema,
        TeamChannelHistorySchema,
        TeamMembershipSchema,
        TeamSchema,
        TeamSearchHistorySchema,
        TermsOfServiceSchema,
        UserSchema,
    ],
});
